### ISSUE TITLE
Don't ask for permission READ_EXTERNAL_STORAGE until necessary

### ISSUE THREAD

**Issue by nbudzyn** [the3soundcrafties/SoundboardCrafter#119]
Currently the system asks for permission to read local files at start-up.

Better ask for permission when the user first clicks on the birthday cake (to switch to local files).

**Comment by nbudzyn** [comment]
Depends on #108

**Comment by nbudzyn** [comment]
Google: "If the user denies or revokes a permission that a feature needs, gracefully degrade your app so that the user can continue using your app, possibly by disabling the feature that requires the permission."

**Comment by nbudzyn** [comment]
@Schneeveilchen

**Comment by Schneeveilchen** [comment]
Information Text "Eigene Sounds verwenden?" add to "Ändern in Android Einstellungen Apps Soundboardcrafter Berechtigungen"
