### ISSUE TITLE
Creating soundboards from assets automatically does not work after uninstall and reinstall

### ISSUE THREAD

**Issue by Schneeveilchen** [the3soundcrafties/SoundboardCrafter#120]
Sound would be not deinstalled

**Comment by Schneeveilchen** [comment]
finished until Sept

**Comment by nbudzyn** [comment]
Android Studio:

> On SDK version 23 and up, your app data will be automatically backed up and restored on app install. 
> Consider adding the attribute android:fullBackupContent to specify an @xml resource which configures which files 
> to backup. More info: https://developer.android.com/training/backup/autosyncapi.html

:-)

**Comment by nbudzyn** [comment]
Let's say: 
- If the user already had some soundboards before uninstalling, they shall keep them. To not duplicate soundboards, we do not insert any soundboards after reinstall in this case.
- But if the user did not have any soundboards when uninstalling - they might deliberately have deleted the soundboards last time - then we are going to  generate new soundboards for them at first app start after reinstall. We must be sure not to insert the same _sounds_ into the database again - so we remove all sounds before inserting the new soundboards.
