### ISSUE TITLE
Create tab for a character

### ISSUE THREAD

**Issue by jfelkel** [the3soundcrafties/SoundboardCrafter#2]
save sounds for a character

**Comment by nbudzyn** [comment]
About the same as #4?

**Comment by nbudzyn** [comment]
Sounds for a character - that's just one more soundboard the user can create, isn't it?

**Comment by nbudzyn** [comment]
> Sounds for a character - that's just one more soundboard the user can create, isn't it?

I guess so. So it's a duplicate or #4.
